apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: sentiment-analysis-api-rule
spec:
  gateway: kyma-system/kyma-gateway
  host: cusrevwh-o
  service:
    name: customer-review-webhook
    port: 80
  rules:
  - accessStrategies:
    - config:
        jwks_urls:
        - {JWKS URL of your IDP} #e.g. SAP Cloud Identity Tenant
        trusted_issuers:
        - {Your IDP address} #e.g. SAP Cloud Identity Tenant
      handler: jwt
    methods:
    - POST
    path: /.*
    service:
      name: customer-review-webhook
      port: 80