apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: customer-review-webhook
spec:
  runtime: nodejs18
  source:
    gitRepository:
      url: https://github.com/SAP-samples/kyma-runtime-extension-samples.git
      baseDir: /sentiment-analysis/lambdas/customer-review-webhook
      reference: main
  env:
    - name: EVENT_NAME
      value: 'sap.kyma.custom.internal.product.reviewsubmitted.v1'

