apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    app: commerce-mock
  name: commerce-mock
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: commerce-mock
    port: 10000
    host: commerce
  rules:
    - path: /.*
      methods: ["GET","POST","PUT","DELETE","HEAD"]
      accessStrategies:
        - handler: allow
