apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-provisioning-demo
  labels:
    app: saas-provisioning-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-provisioning-demo
  template:
    metadata:
      labels:
        app: saas-provisioning-demo
    spec:
      serviceAccountName: "saas-demo-service-account"
      containers:
        - image: 'jcawley5/saas-provisioning-demo:latest'
          imagePullPolicy: Always
          name: saas-provisioning-demo
          env:
          - name: IDP_clientid
            valueFrom:
              secretKeyRef:
                name: saas-prov-xsuaa-binding
                key: clientid
          - name: IDP_clientsecret
            valueFrom:
              secretKeyRef:
                name: saas-prov-xsuaa-binding
                key: clientsecret
          - name: IDP_url
            valueFrom:
              secretKeyRef:
                name: saas-prov-xsuaa-binding
                key: url
          - name: IDP_xsappname
            valueFrom:
              secretKeyRef:
                name: saas-prov-xsuaa-binding
                key: xsappname
          - name: IDP_identityzone
            valueFrom:
              secretKeyRef:
                name: saas-prov-xsuaa-binding
                key: xsappname
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: saas-provisioning-demo

---
apiVersion: v1
kind: Service
metadata:
  name: saas-provisioning-demo
  labels:
    app: saas-provisioning-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: saas-provisioning-demo
