apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: saas-prov-instance
spec:
  serviceOfferingName: saas-registry
  servicePlanName: application
  parameters:
    xsappname: "saas-provisioning-demo-app22"
    displayName: "Kyma SAAS Provisioning Demo"
    description: "A Kyma SAAS Provisioning Demo Sample App"
    category: "Kyma Demo"
    appUrls:
      onSubscription: "https://saas-provisioning-demo.<cluster domain>/callback/v1.0/tenants/{tenantId}"