apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: saas-prov-xsuaa
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    oauth2-configuration:
      redirect-uris:
      - https://*.<cluster domain>/oauth/callback
      - http://localhost:8000/oauth/callback
    xsappname: saas-provisioning-demo-app
    tenant-mode: shared
    scopes:
      - name: "$XSAPPNAME.User"
        description: "User of the application"
      - name: "$XSAPPNAME.Callback"
        description: "With this scope set, the callbacks for tenant onboarding, offboarding and getDependencies can be called."
        grant-as-authority-to-apps:
          - "$XSAPPNAME(application,sap-provisioning,tenant-onboarding)"
    role-templates:
      - name: "User"
        description: "User of the application"
        scope-references:
          - "$XSAPPNAME.User"
    role-collections:
      - name: "saas-provisioning-demo-app-User"
        description: "My SaaS App User"
        role-template-references: 
        - "$XSAPPNAME.User"
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: saas-prov-xsuaa-binding
spec:
  serviceInstanceName: saas-prov-xsuaa