apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-mock
  labels:
    app: marketing-mock
spec:
  selector:
    matchLabels:
      app: marketing-mock
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: marketing-mock
    spec:
      containers:
      - image: ghcr.io/sap-samples/xf-application-mocks/marketing-mock:latest
        imagePullPolicy: Always
        name: mock
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
        - name: RENEWCERT_JOB_CRON
          value: "00 00 */12 * * *"
        volumeMounts:
        - mountPath: "/app/keys"
          name: mock-volume
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
      volumes:
      - name: mock-volume
        persistentVolumeClaim:
          claimName: marketing-mock
---
apiVersion: v1
kind: Service
metadata:
  name: marketing-mock
  labels:
    app: marketing-mock
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: marketing-mock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marketing-mock
  labels:
    app: marketing-mock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
