apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: mssql-api-rule
  namespace: lionel-fridgy
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - POST
        - GET
      path: /.*
  service:
    host: mssql-api-function
    name: mssql-api-function
    port: 80
