
### LOCAL: Call mocked service
POST http://localhost:3000/orders
Content-type: application/json

{
    "orderNo": 123123
}

### LOCAL: Call CDS action which calls mocked service and creates an new order
POST http://localhost:4004/orders/external 
Content-type: application/json
Authorization: Basic kyma:kyma
 
{
    "orderNo": 1231123
}

### LOCAL: Get Orders
GET http://localhost:4004/orders/Orders 
Content-type: application/json
Authorization: Basic kyma:kyma


### REMOTE: Get Access Token -  use the values from the secret orders-srv-auth
# @name accessTokenReq
# @prompt URL
# @prompt  CLIENTID
# @prompt  CLIENTSECRET
POST {{URL}}/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

response_type=token
&grant_type=client_credentials
&client_id={{CLIENTID}}
&client_secret={{CLIENTSECRET}}


### REMOTE: Get Orders
# @prompt API_URL
GET {{API_URL}}/orders/Orders HTTP/1.1
Authorization: Bearer {{accessTokenReq.response.body.access_token}}

### REMOTE: Call CDS action which calls mocked service via the SAP Cloud Connector and creates an new order
# @prompt API_URL
POST {{API_URL}}/orders/external 
Content-type: application/json
Authorization: Bearer {{accessTokenReq.response.body.access_token}}
 
{
    "orderNo": 2211
}