apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: mssql-api-apirule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    path: /.*
  service:
    host: mssql-api-function
    name: mssql-api-service
    port: 3000