apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: mssql-api-function
  labels:
    app: mssql-api-function
    app.kubernetes.io/managed-by: Helm
spec:
  type: git
  runtime: nodejs14
  reference: main
  baseDir: lionel-fridgy/functions/mssql-api/app
  source: github-internal-repo
