# Default values for sample-extension-dotnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gabbi/sample-extension-dotnet:0.0.1
  pullPolicy: Always

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}
