# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import orders_pb2 as orders__pb2


class OrderStub(object):
    """The order service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordOrders = channel.stream_unary(
                '/orders.Order/RecordOrders',
                request_serializer=orders__pb2.OrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderSummary.FromString,
                )
        self.GetOrders = channel.unary_stream(
                '/orders.Order/GetOrders',
                request_serializer=orders__pb2.OrderRequest.SerializeToString,
                response_deserializer=orders__pb2.OrderReply.FromString,
                )


class OrderServicer(object):
    """The order service definition.
    """

    def RecordOrders(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordOrders': grpc.stream_unary_rpc_method_handler(
                    servicer.RecordOrders,
                    request_deserializer=orders__pb2.OrderRequest.FromString,
                    response_serializer=orders__pb2.OrderSummary.SerializeToString,
            ),
            'GetOrders': grpc.unary_stream_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=orders__pb2.OrderRequest.FromString,
                    response_serializer=orders__pb2.OrderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.Order', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Order(object):
    """The order service definition.
    """

    @staticmethod
    def RecordOrders(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/orders.Order/RecordOrders',
            orders__pb2.OrderRequest.SerializeToString,
            orders__pb2.OrderSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orders.Order/GetOrders',
            orders__pb2.OrderRequest.SerializeToString,
            orders__pb2.OrderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
