apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-extension-java.fullname" . }}
  labels:
    {{- include "sample-extension-java.labels" . | nindent 4 }}
data:
  JDBC_URL: {{ .Values.jdbc.url | b64enc }}
  JDBC_USER: {{ .Values.jdbc.user | b64enc }}
  JDBC_PASSWORD: {{ .Values.jdbc.password | b64enc }}
  JDBC_DRIVER: {{ .Values.jdbc.driver | b64enc }}