apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-zone-ha-httpbin
  name: multi-zone-ha-httpbin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-zone-ha-httpbin
  strategy: {}
  template:
    metadata:
      labels:
        app: multi-zone-ha-httpbin
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: multi-zone-ha-httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        name: httpbin
        resources: {}
        ports:
        - containerPort: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multi-zone-ha-httpbin
  name: multi-zone-ha-httpbin
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: multi-zone-ha-httpbin
status:
  loadBalancer: {}
