apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-extension-micronaut
    kyma-grafana: enabled
  name: sample-extension-micronaut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-extension-micronaut
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-extension-micronaut
        kyma-grafana: enabled
    spec:
      containers:
      - image: gabbi/sample-extension-micronaut:0.0.3
        name: sample-extension-micronaut
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: sample-extension-micronaut
              optional: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-extension-micronaut
  name: sample-extension-micronaut
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-extension-micronaut
status:
  loadBalancer: {}
