apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ include "sample-event-trigger-java.fullname" . }}
  labels:
    {{- include "sample-event-trigger-java.labels" . | nindent 4 }}
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: {{ .Values.trigger.source }}  # name of the application/system
      type: {{ .Values.trigger.eventType }} # event type
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: {{ include "sample-event-trigger-java.fullname" . }}
