apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{include "api-mssql-go.fullname" .}}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /orders|/orders/.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
  service:
    host: {{include "api-mssql-go.fullname" .}}
    name: {{include "api-mssql-go.fullname" .}}
    port: {{.Values.service.port}}
