apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-mssql-go.fullname" . }}
  labels:
    {{- include "api-mssql-go.labels" . | nindent 4 }}
data:
  database: {{ .Values.configmap.database }}
  host: {{ include "api-mssql-go.dbhost" . }}
  port: {{ .Values.configmap.port | quote }}
