apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-mssql-go.fullname" . }}
  labels:
    {{- include "api-mssql-go.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "api-mssql-go.selectorLabels" . | nindent 6 }}
  ports:
    - name: http
      protocol: TCP
      port: {{.Values.service.port}}
      targetPort: 8000
