apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: sample-event-trigger-java-subscription
spec:
  filter:
    filters:
      - eventSource:
          property: source
          type: exact
          value: ""
        eventType:
          property: type
          type: exact
          value: sap.kyma.custom.{your-connected-commerce-application-name}.order.created.v1
  sink: http://sample-event-trigger-java.dev.svc.cluster.local
