replicaCount: 1

image:
  repository: gabbi/sample-extension-scala:0.0.1
  pullPolicy: Always

securityContext:
  capabilities:
   drop:
   - ALL
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
