apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-workload-on-prem-reg
  name: test-workload-on-prem-reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workload-on-prem-reg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-workload-on-prem-reg
    spec:
      imagePullSecrets:
      - name: on-premise-reg
      containers:
      - image: localhost:{nginx-reverse-proxy-node-port}/on-prem-nginx:{generate-image-tag}
        name: on-prem-nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-workload-on-prem-reg
  name: test-workload-on-prem-reg
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-workload-on-prem-reg
status:
  loadBalancer: {}
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: test-workload-on-prem-reg
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: test-workload-on-prem-reg
  rules:
  - accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    path: /.*
  service:
    name: test-workload-on-prem-reg
    port: 80
status: {}