apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: sentiment-analysis
spec:
  scaleConfig:
    minReplicas: 1
    maxReplicas: 1
  runtime: nodejs18
  source:
    gitRepository:
      url: https://github.com/SAP-samples/kyma-runtime-extension-samples.git
      baseDir: /sentiment-analysis/lambdas/sentiment-analysis
      reference: main
  env:
    - name: SLACK_URL
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: slackUrl
    - name: BASE_SITE
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: baseSite
    - name: GATEWAY_URL_OCC
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: gateway_url_occ
    - name: GATEWAY_URL_REVIEW
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: gateway_url_review
    - name: GATEWAY_URL_C4C
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: gateway_url_c4c
    - name: SVC_URL_TEXT_ANALYSIS
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: svcUrlTextAnalysis
    - name: SVC_URL_CONTENT_MODERATION
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: svcUrlContentModeration
    - name: C4C_UPDATE_FLAG
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: c4cUpdateFlag
    - name: SALES_CLOUD_V2_GATEWAY_URL
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: salesCloudV2GatewayUrl
    - name: SALES_CLOUD_V2_USER
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: salesCloudV2User
    - name: SALES_CLOUD_V2_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sentiment-analysis
          key: salesCloudV2Password

