apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: sentiment-analysis
  labels:
    app.kubernetes.io/name: sentiment-analysis
  annotations: {}
spec:
  typeMatching: exact
  sink: http://sentiment-analysis.{your-namespace}.svc.cluster.local
  source: ""
  types:
    - sap.kyma.custom.internal.product.reviewsubmitted.v1
