apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-cloudsdk-java
  name: sample-cloudsdk-java
  namespace: mktg-ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-cloudsdk-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-cloudsdk-java
    spec:
      containers:
      - image: gabbi/sample-cloudsdk-java:0.0.1
        imagePullPolicy: Always
        name: sample-cloudsdk-java
        resources: {}
        env:
          - name: APPLICATION_TENANT_NAME
            value: my-mktng-tenant
          - name: APPLICATION_SERVICE_PATH
            value: "/sap/opu/odata/SAP/API_MKT_CAMPAIGN_SRV;v=0002"
          - name: destinations
            value: '[{name: "$(APPLICATION_TENANT_NAME)", url: "$(URL)", username: "$(User)", password: "$(Password)"}]'
        ports:
          - containerPort: 8080
            name: http
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-cloudsdk-java
  name: sample-cloudsdk-java
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: sample-cloudsdk-java
status:
  loadBalancer: {}
