@hostname=https://sample-extension-dotnet-minimalapi.c-6d073c0.kyma-stage.shoot.live.k8s-hana.ondemand.com

### Add a todo item to the list
POST {{hostname}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

### Get all todo items
GET {{hostname}}/todoitems/

### Rewrite a todo item
PUT {{hostname}}/todoitems/1
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

### Delete a todo item
DELETE {{hostname}}/todoitems/1