apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: address-completion-sap-dqs
  labels:
    scenario: address-completion
spec:
  runtime: nodejs18
  source:
    gitRepository:
      url: https://github.com/SAP-samples/kyma-runtime-extension-samples.git
      baseDir: /address-completion-c4c/sales-cloud-address-completion-dqs/function
      reference: main
  env:
  - name: CENTRAL_GW_URL
    valueFrom:
      secretKeyRef:
        name: address-completion-sap-dqs
        key: centralGwUrl
  - name: DQS_UAA
    valueFrom:
      secretKeyRef: 
        name: data-quality-service-sb
        key: uaa
  - name: URI
    valueFrom:
      secretKeyRef:
        name: data-quality-service-sb
        key: uri
