apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  labels:
    scenario: address-completion
  name: address-completion-dqs
spec:
  sink: http://address-completion-sap-dqs.{your-namespace}.svc.cluster.local
  source: {provide-your-application-name-as-shown-in-kyma}
  typeMatching: standard
  types:
    - Account.Root.Updated.v1
    - Account.Root.Created.v1
