apiVersion: v1
kind: Secret
metadata:
  name: prinicpal-prop-on-prem-destinations
type: Opaque
stringData:
  destinations: >-
    [
        {
          "name": "on-prem-backend",
          "url": "http://{your-virtual-host}:{port}",
          "proxyHost": "connectivity-proxy.kyma-system.svc.cluster.local",
          "proxyPort": "20003",
          "forwardAuthToken" : false,
          "timeout": 1200
        }
    ]
---
apiVersion: v1
data:
  xs-app.json: |-
    {
        "authenticationMethod": "route",
        "sessionTimeout": 10,
        "login" : {
          "callbackEndpoint": "/sap/com/onprem/mysales"
        },
        "routes": [
            {
                "source": "^/sap/com/onprem/(.*)$",
                "destination": "on-prem-backend",
                "target": "$1",
                "authenticationType": "xsuaa"
            }
        ]
    }
kind: ConfigMap
metadata:
  name: approuter-config