apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: principal-prop-on-prem-dest
  labels:
    sample: principal-prop-on-prem
spec:
  serviceOfferingName: destination
  servicePlanName: lite
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  labels:
    sample: principal-prop-on-prem
  name: principal-prop-on-prem-dest
spec:
  serviceInstanceName: principal-prop-on-prem-dest
