apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: principal-prop-on-prem-xsuaa
  labels:
    sample: principal-prop-on-prem
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: principal-prop-on-prem
    tenant-mode: dedicated
    scopes:
      - name: "$XSAPPNAME.View"
        description: "View sales"
      - name: "uaa.user"
        description: "uaa"
    role-templates:
      - name: "Token_Exchange"
        description: "UAA"
        scope-references:
          - "uaa.user"
      - name: "Viewer"
        description: "Read Access to Sales data"
        scope-references:
          - "$XSAPPNAME.View"
    oauth2-configuration:
      redirect-uris:
        # callback
        - "https://principal-prop-on-prem.{your-cluster-domain}/**"
        - "http://localhost:5000/**"
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: principal-prop-on-prem-xsuaa
  labels:
    sample: principal-prop-on-prem
spec:
  serviceInstanceName: principal-prop-on-prem-xsuaa
