apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-extension-dotnet
  name: sample-extension-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-extension-dotnet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-extension-dotnet
    spec:
      containers:
      - image: gabbi/sample-extension-dotnet:0.0.1
        name: sample-extension-dotnet
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-extension-dotnet
  name: sample-extension-dotnet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-extension-dotnet
  type: ClusterIP
status:
  loadBalancer: {}
