apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: api-mssql-go
spec:
  hosts:
    - api-mssql-go
  service:
    name: api-mssql-go
    port: 80
  gateway: kyma-system/kyma-gateway
  corsPolicy: 
    allowHeaders:
      - Content-Type
    allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowOrigins:
      - regex: ".*{YOUR_DOMAIN}"
  rules:
    - path: "/orders"
      methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      noAuth: true
    - path: "/orders/{**}"
      methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      noAuth: true