apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: api-mssql-go-event-sub
  namespace: dev
spec:
  typeMatching: exact
  source: ""
  types:
    - sap.kyma.custom.mp-commerce-mock.order.created.v1
  sink: http://api-mssql-go.dev.svc.cluster.local:80/orderCodeEvent