apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: api-mssql-go-event-sub
  labels: {}
  annotations: {}
  namespace: dev
spec:
  typeMatching: standard
  sink: http://api-mssql-go.dev.svc.cluster.local/orderCodeEvent
  source: mp-commerce-mock
  types:
    - order.received.v1
    - order.changed.v1