apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: sample-angular-app
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: sample-angular-app
    name: kyma-identity-propagation-spa
    port: 80
