apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: slack-messenger-function-subscriber
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.lionelfridgy.alert.triggered.v1
  protocol: ""
  protocolsettings: {}
  sink: http://slack-messenger-function.lionel-fridgy.svc.cluster.local