apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: use-azure-redis-cache
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - path: /.*
    accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    - POST
  service:
    host: use-azure-redis-cache
    name: use-azure-redis-cache
    port: 80