apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: delayedorderemailsender
  spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
      path: /.*
  service:
    host: delayedorderemailsender.<YOUR HOST>
    name: delayedorderemailsender
    port: 80