apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-scala-extension
  name: my-scala-extension
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-scala-extension
  type: ClusterIP
status:
  loadBalancer: {}
