spring:
  datasource:
    url: TBA
    username: TBA
    password: TBA
    driverClassName: TBA
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  forward-headers-strategy: framework
  use-forward-headers: true