spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: kyma4ever
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect