apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-observer-deployment
  labels:
    app: bot-observer
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-observer
  template:
    metadata:
      labels:
        app: bot-observer
    spec:
      containers:
      - name: display-bot-knowledge
        image: <image-name> #lasseurban/bot-observer-tool     #change it to your image
        ports:
        - name: https
          containerPort: 3000
        env:
          - name: CAI_CREDENTIALS_URL
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: cai-credentials-url
          - name: CAI_CREDENTIALS_ID
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: cai-credentials-id
          - name: CAI_CREDENTIALS_SECRET
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: cai-credentials-secret
          - name: BOT_URL
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: bot-url
          - name: X_TOKEN
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: cai-x-token
          - name: STACK_URL
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: stack-url      
          - name: STACK_TAG
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: stack-tag
          - name: STACK_KEY
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: stack-key
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: db-name
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: db-host
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: db-username
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: bot-secret
                key: db-password
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: bot-observer-service 
  labels:
    app: bot-observer-service
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: bot-observer
  ports:
  - name: https
    port: 3000
    targetPort: 3000
