apiVersion: v1
data:
  nginx.conf: |
    worker_processes  3;
    error_log  /dev/stdout info;
    events {
      worker_connections  10240;
    }
    http {
      access_log  /dev/stdout;
      server {
        listen 8080;
        location / {
          proxy_http_version 1.1;
          proxy_socket_keepalive on;
          proxy_redirect off;
          proxy_set_header Host "myregistry.kyma:25002";
          proxy_set_header X-Forwarded-Host "myregistry.kyma:25002";
          proxy_pass "http://connectivity-proxy.kyma-system.svc.cluster.local:20003";
        }
      }
    }
kind: ConfigMap
metadata:
  name: nginx-conf
