apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-keda-cron-nginx
  name: test-keda-cron-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-keda-cron-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-keda-cron-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}