apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-keda-cron-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-keda-cron-nginx
  pollingInterval: 10
  # immediately scale down the workload
  cooldownPeriod: 0
  # The workload is ASLEEP by DEFAULT, otherwise, it's Awake.
  minReplicaCount: 0
  triggers:
    - type: cron
      metadata:
        # The acceptable values would be a value from the IANA Time Zone Database.
        timezone: Europe/Berlin  
        # At 08:00 AM, Monday through Friday
        start: 0 8 * * 1-5
        # At 06:00 PM, Monday through Friday
        end: 0 18 * * 1-5
        # ie. Your MINIMUM replica count for this workload
        desiredReplicas: "1"