apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ include "sample-extension-java.fullname" . }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /.*
  service:
    host: {{ .Chart.Name }}
    name: {{ include "sample-extension-java.fullname" . }}
    port: 80