apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-extension-java.fullname" . }}
  labels:
    {{- include "sample-extension-java.labels" . | nindent 4 }}
data:
  clusterDomain: {{ .Values.cluster.domain | b64enc }}
  password: {{ .Values.db.user | b64enc }}
  username: {{ .Values.db.password | b64enc }}