apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: consumer
  labels:
    scenario: in-cluster-events
spec:
  baseDir: in-cluster-events/functions-javascript/consumer
  reference: main
  runtime: nodejs14
  source: in-cluster-events-functions
  type: git
