apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: event-consumer
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.internal.product.viewed.v1
  protocol: ""
  protocolsettings: {}
  sink: http://consumer.dev.svc.cluster.local #this is the service name and port