apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: fe-ui5-mssql
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - fe-ui5-mssql
  rules:
    - methods:
        - GET
      noAuth: true
      path: /*
  service:
    name: fe-ui5-mssql
    port: 80