apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: fe-ui5-mssql
spec:
  gateway: kyma-system/kyma-gateway
  host: fe-ui5-mssql
  service:
    name: fe-ui5-mssql
    port: 80
  rules:
    - path: /*
      methods: ["GET"]
      noAuth: true