apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: text-analysis
spec:
  runtime: python39
  source:
    gitRepository:
      url: https://github.com/SAP-samples/kyma-runtime-extension-samples.git
      baseDir: /sentiment-analysis/lambdas/text-analysis
      reference: main
      auth:
        type: basic
        secretName: git-creds-basic