apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: receiver-apirule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - POST
    path: /.*
  service:
    host: receiver
    name: receiver-service
    port: {{ .Values.service.port }}
