# Default values for database-mssql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: jcawley5/fe-ui5-mssql
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  port: 80

clusterDomain: "you must override this value"

api-mssql-go:
  nameOverride: "api-mssql-go"
