apiVersion: v1
kind: Secret
metadata:
  name: lionel-fridgy-secret
  labels:
    app: lionel-fridgy-secret
type: Opaque
stringData:
  db-name: LionelFridgyDB
  db-host: mssql.lionel-fridgy.svc.cluster.local
  db-username: sa
  db-password: mfrCPTK3