apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  labels:
    app: bot-secret
type: Opaque
stringData:
  cai-credentials-url: {{ .Values.bot.secret.caicredentialsurl }}  
  cai-credentials-id: {{ .Values.bot.secret.caicredentialsid }} 
  cai-credentials-secret: {{ .Values.bot.secret.caicredentialssecret }} 
  bot-url: {{ .Values.bot.secret.boturl }} 
  cai-x-token: {{ .Values.bot.secret.caixtoken }}
  stack-url: {{ .Values.bot.secret.stackurl }}
  stack-tag: {{ .Values.bot.secret.stacktag }}
  stack-key: {{ .Values.bot.secret.stackkey | quote }}
  db-name: {{ .Values.bot.secret.dbname }}
  db-host: {{ .Values.bot.secret.dbhost }}
  db-username: {{ .Values.bot.secret.dbusername }}
  db-password: {{ .Values.bot.secret.dbpassword }}
