apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: lionel-fridgy-web-ui-apirule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
  service:
    host: lionel-fridgy-web-ui
    name: lionel-fridgy-web-ui
    port: 80