kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "database-mssql.fullname" . }}
  labels: 
    {{- include "database-mssql.labels" . | nindent 4 }}
spec:
  accessModes: 
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
