apiVersion: v1
kind: Secret
metadata:
  name: {{include "database-mssql.fullname" .}}
  labels: 
  {{- include "database-mssql.labels" . | nindent 4}}
type: Opaque
data:
  username: {{.Values.secret.db.user | b64enc}}
  password: {{.Values.secret.db.password | b64enc}}
