apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-mssql.fullname" . }}
  labels:
    {{- include "database-mssql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "database-mssql.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: 1433
