kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "frontend-ui5-mssql.fullname" . }}
  labels:
    {{- include "frontend-ui5-mssql.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "API_URL": {{ include "frontend-ui5-mssql.apiurl" . }}
    }