apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-ui5-mssql.fullname" . }}
  labels:
    {{- include "frontend-ui5-mssql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "database-mssql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend-ui5-mssql.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "frontend-ui5-mssql.fullname" . }}

