apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-ui5-mssql.fullname" . }}
  labels:
    {{- include "frontend-ui5-mssql.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
  selector:
    {{- include "frontend-ui5-mssql.selectorLabels" . | nindent 6 }}
