name: Build docker sample-extension-java

on:
  push:
    branches: [ main ]
    paths:
    - "sample-extension-java/**"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
env:
  SAMPLE_NAME: sample-extension-java
jobs:

  build:
    defaults:
      run:
        working-directory: sample-extension-java
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3.3.0
      with:
        java-version: 17
        distribution: adopt
    - name: Gradle Build and then Build the Docker image
      run: make build-image
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      if: ${{ failure() }}
      env:
        SLACK_MESSAGE: 'Build Failed for ${{ env.SAMPLE_NAME }}'
        SLACK_WEBHOOK: ${{ secrets.BUILD_FAIL_NOTIFY_SLACK_URL }}
