name: Build and publish container image for the UI5 frontend MS SQL

on:
  workflow_dispatch: {}
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: frontend-ui5-mssql
  LABEL: 1.0.0

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry (GH Packages)
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ env.LABEL }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.0
        with:
          context: "{{defaultContext}}:dsagtt22/ordermicroservice/frontend-ui5-mssql" 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}            
