name: Links Watcher

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  issues: write 

jobs:
  links-watcher:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - name: Check Links in README
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress --max-concurrency 2 --exclude-mail --exclude-loopback './**/*.md'
          output: ./lychee/out.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Create issue when fail
        uses: peter-evans/create-issue-from-file@v4
        if: ${{ steps.lychee.outputs.exit_code }} != 0
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: broken link, automated issue
